#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_AXI_BRAM_CTRL_0_COMPATIBLE "xlnx,axi-bram-ctrl-4.1"
#define XPAR_AXI_BRAM_CTRL_0_BASEADDR 0xc0000000
#define XPAR_AXI_BRAM_CTRL_0_HIGHADDR 0xc0007fff
#define XPAR_AXI_BRAM_CTRL_0_BRAM_DATA_WIDTH 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_ECC_PRESENT 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_FAULT_INJECTION_PRESENT 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_CORRECTABLE_FAILING_REGISTERS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_CORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_UNCORRECTABLE_FAILING_REGISTERS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_UNCORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_ECC_STATUS_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_CORRECTABLE_COUNTER_BITS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_ECC_ON_OFF_REGISTER 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_ECC_ON_OFF_RESET_VALUE 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_WRITE_ACCESS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_MEM_BASE_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_MEM_HIGH_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_MEM_CTRL_BASE_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_0_BRAM_MEM_CTRL_HIGH_ADDRESS 0x0

/* Canonical definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_XBRAM_0_BASEADDR 0xc0000000
#define XPAR_XBRAM_0_HIGHADDR 0xc0007fff
#define XPAR_XBRAM_0_BRAM_DATA_WIDTH 0x0
#define XPAR_XBRAM_0_BRAM_ECC_PRESENT 0x0
#define XPAR_XBRAM_0_BRAM_FAULT_INJECTION_PRESENT 0x0
#define XPAR_XBRAM_0_BRAM_CORRECTABLE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_BRAM_CORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_XBRAM_0_BRAM_UNCORRECTABLE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_BRAM_UNCORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_XBRAM_0_BRAM_ECC_STATUS_INTERRUPT_PRESENT 0x0
#define XPAR_XBRAM_0_BRAM_CORRECTABLE_COUNTER_BITS 0x0
#define XPAR_XBRAM_0_BRAM_ECC_ON_OFF_REGISTER 0x0
#define XPAR_XBRAM_0_BRAM_ECC_ON_OFF_RESET_VALUE 0x0
#define XPAR_XBRAM_0_BRAM_WRITE_ACCESS 0x0
#define XPAR_XBRAM_0_BRAM_MEM_BASE_ADDRESS 0x0
#define XPAR_XBRAM_0_BRAM_MEM_HIGH_ADDRESS 0x0
#define XPAR_XBRAM_0_BRAM_MEM_CTRL_BASE_ADDRESS 0x0
#define XPAR_XBRAM_0_BRAM_MEM_CTRL_HIGH_ADDRESS 0x0
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,axi-bram-ctrl-4.1"

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x2580
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x2580
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0xffff
#define XPAR_AXI_BRAM_0_BASEADDRESS 0xc0000000
#define XPAR_AXI_BRAM_0_HIGHADDRESS 0xc0007fff
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_ADDR_SIZE 32

#define STDOUT_BASEADDRESS 0x40600000
#define STDIN_BASEADDRESS 0x40600000

/* Device ID */
#define XPAR_DEVICE_ID "7a35t"

#endif  /* end of protection macro */