# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    C:/Users/andre/Desktop/snn-fpga/src/hdl
    C:/Users/andre/Desktop/snn-fpga/src/hdl/bram
    C:/Users/andre/Desktop/snn-fpga/src/hdl/snn
    C:/Users/andre/Desktop/snn-fpga/src/hdl/fifo
    C:/Users/andre/Desktop/snn-fpga/src/hdl/bram/mem
    c:/Users/andre/Desktop/snn-fpga/vivado/snn_fpga/snn_fpga.gen/sources_1/bd/microblaze/ipshared/3cbc
    c:/Users/andre/Desktop/snn-fpga/vivado/snn_fpga/snn_fpga.gen/sources_1/bd/microblaze/ipshared/f0b6/hdl/verilog
    c:/Users/andre/Desktop/snn-fpga/vivado/snn_fpga/snn_fpga.gen/sources_1/bd/microblaze/ipshared/0127/hdl/verilog
  } {
      C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -sv -include {
    C:/Users/andre/Desktop/snn-fpga/src/hdl
    C:/Users/andre/Desktop/snn-fpga/src/hdl/bram
    C:/Users/andre/Desktop/snn-fpga/src/hdl/snn
    C:/Users/andre/Desktop/snn-fpga/src/hdl/fifo
    C:/Users/andre/Desktop/snn-fpga/src/hdl/bram/mem
    c:/Users/andre/Desktop/snn-fpga/vivado/snn_fpga/snn_fpga.gen/sources_1/bd/microblaze/ipshared/3cbc
    c:/Users/andre/Desktop/snn-fpga/vivado/snn_fpga/snn_fpga.gen/sources_1/bd/microblaze/ipshared/f0b6/hdl/verilog
    c:/Users/andre/Desktop/snn-fpga/vivado/snn_fpga/snn_fpga.gen/sources_1/bd/microblaze/ipshared/0127/hdl/verilog
  } C:/Users/andre/Desktop/snn-fpga/src/hdl/top_microblaze.sv
      rt::read_verilog -include {
    C:/Users/andre/Desktop/snn-fpga/src/hdl
    C:/Users/andre/Desktop/snn-fpga/src/hdl/bram
    C:/Users/andre/Desktop/snn-fpga/src/hdl/snn
    C:/Users/andre/Desktop/snn-fpga/src/hdl/fifo
    C:/Users/andre/Desktop/snn-fpga/src/hdl/bram/mem
    c:/Users/andre/Desktop/snn-fpga/vivado/snn_fpga/snn_fpga.gen/sources_1/bd/microblaze/ipshared/3cbc
    c:/Users/andre/Desktop/snn-fpga/vivado/snn_fpga/snn_fpga.gen/sources_1/bd/microblaze/ipshared/f0b6/hdl/verilog
    c:/Users/andre/Desktop/snn-fpga/vivado/snn_fpga/snn_fpga.gen/sources_1/bd/microblaze/ipshared/0127/hdl/verilog
  } {
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_clk_wiz_0_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_axi_uartlite_0_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_rst_clk_wiz_0_100M_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_axi_bram_ctrl_0_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_axi_bram_ctrl_1_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_axi_bram_ctrl_2_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_axi_bram_ctrl_3_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_axi_smc_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_microblaze_0_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_dlmb_v10_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_ilmb_v10_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_dlmb_bram_if_cntlr_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_ilmb_bram_if_cntlr_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_lmb_bram_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_mdm_1_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/realtime/microblaze_axi_gpio_0_0_stub.v
      C:/Users/andre/Desktop/snn-fpga/vivado/snn_fpga/snn_fpga.gen/sources_1/bd/microblaze/synth/microblaze.v
      C:/Users/andre/Desktop/snn-fpga/vivado/snn_fpga/snn_fpga.gen/sources_1/bd/microblaze/hdl/microblaze_wrapper.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top_microblaze
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter linterFlow true
    rt::set_parameter synthReportEmptyAndUndriven false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/andre/Desktop/snn-fpga/vivado/.Xil/Vivado-8168-DESKTOP-OVIC86T/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
