domain_path: /home/andrew/Desktop/snn-soc/vitis/ws/platform/export/platform/sw/standalone_microblaze_0
app_src_dir: /home/andrew/.Xilinx/Vitis/2024.1/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
